name: Build Docker Images

on: push

jobs:
  cmake:
    name: "CMake Docker builds"
    strategy:
      fail-fast: false
      matrix:
        cmake_version: ['3.21.6', '3.22.3']
        clang_major: [12, 13, 14]
        gcc_major: [9, 10, 11]
        qt_version: ['6.2.4']

        include:
          - cmake_version: '3.22.3'
            clang_major: 14
            gcc_major: 11
            qt_version: '6.2.4'
            gcc_tags: arbmind/cmake-gcc:latest
            gcc_qt_tags: arbmind/cmake-gcc-qt:latest
            clang_tags: arbmind/cmake-clang:latest
            clang_libstdcpp_tags: arbmind/cmake-clang-libstdcpp:latest
            clang_libstdcpp_qt_tags: arbmind/cmake-clang-libstdcpp-qt:latest

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: CMake ${{ matrix.cmake_version }} + GCC ${{ matrix.gcc_major }}
        uses: docker/build-push-action@v2
        with:
          # buildkitd-flags: --debug
          target: cmake-gcc
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/cmake-gcc:${{ matrix.cmake_version }}-${{ matrix.gcc_major }}
            ${{ matrix.gcc_tags }}
          build-args: |
            GCC_MAJOR=${{ matrix.gcc_major }}
            QT_VERSION=${{ matrix.qt_version }}
            CMAKE_VERSION=${{ matrix.cmake_version }}

      - name: CMake ${{ matrix.cmake_version }} + GCC ${{ matrix.gcc_major }} + Qt ${{ matrix.qt_version }}
        uses: docker/build-push-action@v2
        with:
          target: cmake-gcc-qt
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/cmake-gcc-qt:${{ matrix.cmake_version }}-${{ matrix.gcc_major }}-${{ matrix.qt_version }}
            ${{ matrix.gcc_qt_tags }}
          build-args: |
            GCC_MAJOR=${{ matrix.gcc_major }}
            QT_VERSION=${{ matrix.qt_version }}
            CMAKE_VERSION=${{ matrix.cmake_version }}

      - name: CMake ${{ matrix.cmake_version }} + Clang ${{ matrix.clang_major }}
        uses: docker/build-push-action@v2
        with:
          target: cmake-clang
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/cmake-clang:${{ matrix.cmake_version }}-${{ matrix.clang_major }}
            ${{ matrix.clang_tags }}
          build-args: |
            CLANG_MAJOR=${{ matrix.clang_major }}
            QT_VERSION=${{ matrix.qt_version }}
            CMAKE_VERSION=${{ matrix.cmake_version }}

      - name: CMake ${{ matrix.cmake_version }} + Clang ${{ matrix.clang_major }} + LibStdC++ ${{ matrix.gcc_major }}
        uses: docker/build-push-action@v2
        with:
          target: cmake-clang-libstdcpp
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/cmake-clang-libstdcpp:${{ matrix.cmake_version }}-${{ matrix.clang_major }}-${{ matrix.gcc_major }}
            ${{ matrix.clang_libstdcpp_tags }}
          build-args: |
            CLANG_MAJOR=${{ matrix.clang_major }}
            GCC_MAJOR=${{ matrix.gcc_major }}
            QT_VERSION=${{ matrix.qt_version }}
            CMAKE_VERSION=${{ matrix.cmake_version }}

      - name: CMake ${{ matrix.cmake_version }} + Clang ${{ matrix.clang_major }} + LibStdC++ ${{ matrix.gcc_major }} + Qt ${{ matrix.qt_version }}
        uses: docker/build-push-action@v2
        with:
          target: cmake-clang-libstdcpp-qt
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            arbmind/cmake-clang-libstdcpp-qt:${{ matrix.cmake_version }}-${{ matrix.clang_major }}-${{ matrix.gcc_major }}-${{ matrix.qt_version }}
            ${{ matrix.clang_libstdcpp_qt_tags }}
          build-args: |
            CLANG_MAJOR=${{ matrix.clang_major }}
            GCC_MAJOR=${{ matrix.gcc_major }}
            QT_VERSION=${{ matrix.qt_version }}
            CMAKE_VERSION=${{ matrix.cmake_version }}
